export const TIMEOUT_SITUATION = {
  DISCUSSION: 15,
  ARGUMENT: 9,
  VOTE: 15,
  MAFIA: 3,
  DOCTOR: 2,
  POLICE: 20,
  INTERMISSION: 10,
} as const;

export type TIMEOUT_SITUATION = typeof TIMEOUT_SITUATION[keyof typeof TIMEOUT_SITUATION];