export const errorCode = {
  GAME_INVALID_PLAYER_COUNT_ERROR: 1000,
  ROLE_COUNT_NEGATIVE_ERROR: 1001,
  NOT_FOUND_GAME_HISTORY_ERROR: 1002,
  NOT_FOUND_USER_ERROR:1003,
  NOT_FOUND_GAME_USER_ERROR:1004,
};