export const EXCEPTION_CODE = {
  GAME_INVALID_PLAYER_COUNT_EXCEPTION: 1000,
  ROLE_COUNT_NEGATIVE_EXCEPTION: 1001,
  NOT_FOUND_GAME_HISTORY_EXCEPTION: 1002,
  NOT_FOUND_USER_EXCEPTION: 1003,
  NOT_FOUND_GAME_USER_EXCEPTION: 1004,
  DUPLICATE_TIMER_EXCEPTION: 1005,
  NOT_FOUND_TIMER_EXCEPTION: 1006,
} as const;